//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRecipeBook.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErroMensage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErroMensage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyRecipeBook.Exceptions.ResourceErroMensage", typeof(ResourceErroMensage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A categoria é inválida..
        /// </summary>
        public static string Category_Invalid {
            get {
                return ResourceManager.GetString("Category_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email e a senha devem ser preenchidos..
        /// </summary>
        public static string Email_And_Password_Empty {
            get {
                return ResourceManager.GetString("Email_And_Password_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email do usuário é obrigatório.
        /// </summary>
        public static string Email_Empty {
            get {
                return ResourceManager.GetString("Email_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email deve ser válido.
        /// </summary>
        public static string Email_Invalid {
            get {
                return ResourceManager.GetString("Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email e/ou senha inválido..
        /// </summary>
        public static string Email_Or_Password_Invalid {
            get {
                return ResourceManager.GetString("Email_Or_Password_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas devem ser diferentes..
        /// </summary>
        public static string Equal_Password {
            get {
                return ResourceManager.GetString("Equal_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O igrediente deve ter um nome..
        /// </summary>
        public static string Ingredient_Name_Empty {
            get {
                return ResourceManager.GetString("Ingredient_Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade do igrediente está vazia..
        /// </summary>
        public static string Ingredient_Quantity_Empty {
            get {
                return ResourceManager.GetString("Ingredient_Quantity_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unidade de medida é invalida..
        /// </summary>
        public static string Ingredient_UnitMeasure_Invalid {
            get {
                return ResourceManager.GetString("Ingredient_UnitMeasure_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lista de ingredientes estrá vazia..
        /// </summary>
        public static string Ingredients_Empty {
            get {
                return ResourceManager.GetString("Ingredients_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O modo de preparo está vazio..
        /// </summary>
        public static string MethodPrepar_Empty {
            get {
                return ResourceManager.GetString("MethodPrepar_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuario é obrigatório.
        /// </summary>
        public static string Name_Empty {
            get {
                return ResourceManager.GetString("Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nova senha deve ser preenchida..
        /// </summary>
        public static string New_Password_Empty {
            get {
                return ResourceManager.GetString("New_Password_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário não tem permissão para acessar.
        /// </summary>
        public static string No_Permision {
            get {
                return ResourceManager.GetString("No_Permision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrada nenhuma receita..
        /// </summary>
        public static string No_Recipe {
            get {
                return ResourceManager.GetString("No_Recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há token válido na requisição..
        /// </summary>
        public static string No_Token {
            get {
                return ResourceManager.GetString("No_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter ao menos um numero e uma letra miúscula..
        /// </summary>
        public static string Password_Character {
            get {
                return ResourceManager.GetString("Password_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha é obrigatório.
        /// </summary>
        public static string Password_Empty {
            get {
                return ResourceManager.GetString("Password_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A deve conter no mínimo 6 caractéries.
        /// </summary>
        public static string Password_Length_Invalid {
            get {
                return ResourceManager.GetString("Password_Length_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tempo de preparo deve ser maior que zero..
        /// </summary>
        public static string Time_Zero {
            get {
                return ResourceManager.GetString("Time_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A receita deve conter um titulo..
        /// </summary>
        public static string Title_Empty {
            get {
                return ResourceManager.GetString("Title_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aconteceu um erro desconhecido.
        /// </summary>
        public static string Unkow_Error {
            get {
                return ResourceManager.GetString("Unkow_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email já registrado..
        /// </summary>
        public static string User_Registred {
            get {
                return ResourceManager.GetString("User_Registred", resourceCulture);
            }
        }
    }
}
